spring:
  cloud:
    config:
      name: project-gateway
      uri: http://localhost:8888

eureka:
  instance:
    preferIpAddress:  true
  client:
    registerWithEureka: true
    fetchRegistry:  true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/